export const LOAD_OPPR_SUCCESS = 'LOAD_OPPR_SUCCESS';  
export const LOAD_OPPR_BG_SUCCESS = 'LOAD_OPPR_BG_SUCCESS';
export const UPDATE_OPPR_SUCCESS = 'UPDATE_OPPR_SUCCESS';
export const LOAD_OPPRID_SUCCESS = 'LOAD_OPPRID_SUCCESS';
export const LOAD_MAPS_SUCCESS = 'LOAD_MAPS_SUCCESS';
export const LOAD_SKILLS_SUCCESS = 'LOAD_SKILLS_SUCCESS';
export const LOAD_SKILLSBG_SUCCESS = 'LOAD_SKILLSBG_SUCCESS';